Hw03 mongodb
AdamczukPawel/nodejs-homework pull request #2
Opened 2023-04-28 21:33 UTC by AdamczukPawel

2023-04-29 12:55 UTC, RadziuMM requested changes

2023-04-29 12:55 UTC, RadziuMM commented on routes/api/contacts.js
> +router.patch("/:contactID/favorite", async (req, res, next) => {
1. Brakuje walidacji(joi)
2. contactID => contactId

2023-04-30 20:49 UTC, AdamczukPawel commented
HW3 fix2

2023-04-30 20:54 UTC, RadziuMM approved these changes

2023-05-01 15:37 UTC, merged